import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  return (
    <div
      style={{
        backgroundImage: `url("https://picsum.photos/1920/1080")`,
      }}
      className="w-screen h-screen bg-gray-900 text-gray-200"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <div className="inline-flex shadow-md absolute bottom-8 left-8 p-4 rounded-lg border-2 border-gray-500 bg-gray-800 text-xl items-center">
          <div className="inline-flex mr-4 rounded-full border-2 transition-colors border-gray-600 hover:border-gray-400">
            <Image
              src="https://github.com/RazerMoon.png"
              width="60"
              height="60"
              alt="avatar"
              onClick={() => router.push("https://github.com/RazerMoon")}
              className="rounded-full cursor-pointer"
            />
          </div>
          Hi, I&apos;m Peter
        </div>
      </main>
    </div>
  );
}
