import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import DiscordIcon from "../components/DiscordIcon";
import TwitterIcon from "../components/TwitterIcon";

export default function Home() {
  const router = useRouter();

  return (
    <div
      style={{
        backgroundImage: `url("https://picsum.photos/1920/1080")`,
      }}
      className="w-screen h-screen flex justify-center items-center bg-no-repeat bg-center bg-cover bg-gray-900 text-gray-200 text-sm md:text-base"
    >
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <div className="flex flex-col shadow-md md:absolute m-2 md:m-0 md:bottom-8 md:left-8 p-4 sm:p-8 rounded-md border-2 border-gray-500 bg-gray-800 font-light">
          <div className="flex mb-4 items-center">
            <div className="inline-flex w-max mr-4 rounded-full border-2 transition-colors border-gray-600 hover:border-gray-400">
              <Image
                src="https://github.com/RazerMoon.png"
                width="60"
                height="60"
                alt="avatar"
                onClick={() => router.push("https://github.com/RazerMoon")}
                className="rounded-full cursor-pointer"
              />
            </div>
            <span className="text-lg md:text-xl font-normal">
              Hi, I&apos;m Peter
            </span>
          </div>
          <ul className="ml-4 list-disc list-inside mb-6">
            <li className="mb-2">
              🌱 I’m currently working on my TypeScript skills
            </li>
            <li className="mb-2">🥅 2021 Goals: Get a college scholarship</li>
            <li className="mb-2">⚡ Fun fact: I love to play the piano</li>
          </ul>
          <span className="mb-2 heading">Good books</span>
          <ul className="ml-4 mb-6 list-disc list-inside">
            <li className="mb-2">
              <a href="https://refactoringui.com/book/">Refactoring UI</a> by
              Steve Schoger, Adam Wathan
            </li>
            <li>
              <a href="https://docker.farhan.info/">The Docker Handbook</a> by
              Farhan Hasin Chowdhury
            </li>
          </ul>
          <span className="mb-2 heading">Connect with me</span>
          <div className="ml-4 inline-flex">
            <a
              className="mr-8"
              href="https://discordhub.com/profile/162970149857656832"
            >
              <DiscordIcon />
            </a>
            <a href="https://twitter.com/RazerMoonPL">
              <TwitterIcon />
            </a>
          </div>
        </div>
      </main>
    </div>
  );
}
